---

- name: Load a varfile based on the OS
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ensure CA destination directory exists
  become: true
  file:
    path: "{{ ca_certs_dest }}"
    state: directory
    group: "{{ ca_certs_user }}"
    owner: "{{ ca_certs_group }}"
    mode: 0755
  loop: "{{ ca_certs }}"
  loop_control:
    loop_var: ca
  tags: [install, ca]

- name: Add ca certificates
  become: true
  copy:
    dest: "{{ ca_certs_dest }}/{{ ca | basename }}"
    src: "{{ ca }}"
    group: "{{ ca_certs_user }}"
    owner: "{{ ca_certs_group }}"
    mode: "0644"
  notify: update_certs
  loop: "{{ ca_certs }}"
  loop_control:
    loop_var: ca
  tags: [install, ca]

- include_tasks: python.yml
  when: ca_certs_update_certifi|bool

